# Generated by Django 4.1.1 on 2023-02-24 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_alter_product_product_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_cat',
            field=models.CharField(choices=[('S', 'Shirt'), ('TS', 'T-shirt'), ('P', 'Pant'), ('SH', 'Shoes'), ('C', 'Casuls'), ('A', 'Accessories'), ('IN', 'Innerwears')], max_length=5),
        ),
    ]
