# Generated by Django 4.1.1 on 2023-02-24 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_alter_product_product_cat'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
